# Generated by Django 4.2 on 2023-04-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда Рейтинга', 'verbose_name_plural': 'Звезды Рейтинга'},
        ),
    ]
